/**
 * Generated-foundation mode — produce a BESPOKE single-file HTML landing shell
 * for a prospect from their brand kit, with the Divinci chat injected as an
 * iframe of our own worker's /embed/ route (the real branded SDK chat island +
 * worker HMAC signing + per-email quota). The shell is generated; the chat is
 * the same hardened SDK integration the template uses.
 *
 * The prompt is STRUCTURED + fact-disciplined (fixed sections, explicit design
 * rules drawn from the template's hard-won polish lessons, no invented facts)
 * to keep output consistent across clients — the key risk for autonomous use.
 */
import { execFileSync } from "node:child_process";
import { writeFileSync } from "node:fs";
import { renderExampleChat, injectExampleChat, type TranscriptCopy } from "./example-chat.js";
import { polishFoundation } from "./foundation-polish.js";
import { runClaudeSync } from "./claude-cli.js";

export interface FoundationKit {
  org: string;            // "MD Spine Care"
  productName: string;    // "MD Spine Care AI"
  tagline: string;        // hero headline
  valueProp: string;      // one/two-sentence subhead
  palette: { primary: string; accent: string; mid: string; cream: string; soft: string; text: string };
  fontFamily: string;
  fontLink?: string;      // Google Fonts css2 url
  logoUrl: string;
  logoIsLight: boolean;
  corpusStats: { value: string; label: string }[];
  team: { name: string; title: string; image?: string }[];
  hasLogin: boolean;
  mainSite: string;
  embedUrl: string;       // iframe src for the chat (our /embed/ route)
  /** Per-client example conversation (from copy-gen's en.ts `transcript` block).
   *  Rendered deterministically + spliced in — NOT generated by the LLM. */
  transcript?: TranscriptCopy;
  /** Opening greeting shown atop the example chat (en.ts chat.welcomeMessage). */
  welcomeMessage?: string;
  /** "Documents being indexed" video (Imagen→Veo→R2) for the #how corpus section. */
  corpusVideo?: { videoUrl: string; posterUrl?: string };
  /** Abstract ambient art (Imagen) for a faint full-bleed hero background. */
  heroImageUrl?: string;
  /** Optional drfuhrman-style feature videos (Imagen→Veo→R2). When present, the
   *  page adds a "What's coming" section: native mobile app w/ photo recognition
   *  (multimodal) + on-device/offline. */
  featureVideos?: {
    mobileApp?: { videoUrl: string; posterUrl: string };
    offline?: { videoUrl: string; posterUrl: string };
  };
  /** QA test results from the pipeline's scored-QA run (divinci qa multi-release-run). */
  qaScore?: number;
  qaPassedCount?: number;
  qaTestCount?: number;
  /** Run result ID for a link to the full QA run page. */
  qaRunId?: string;
  /** Suite ID for a link to the QA suite report. */
  qaSuiteId?: string;
  /** White-label workspace ID (needed to build QA report URLs). */
  workspaceId?: string;
  /** Conversation starter question chips shown between the example-chat and team sections. */
  conversationStarters?: string[];
}

/** Initials for a member without a photo (mirrors the template avatar). */
function initials(name: string): string {
  const w = name.replace(/^dr\.?\s+/i, "").trim().split(/\s+/);
  return (w[0]?.[0] ?? "") + (w[w.length - 1]?.[0] ?? "");
}

export function buildFoundationPrompt(kit: FoundationKit): string {
  const team = kit.team
    .map((m) => `  - ${m.name} — ${m.title} — ${m.image ? `photo: ${m.image}` : `NO photo (navy circle, white initials "${initials(m.name).toUpperCase()}")`}`)
    .join("\n");
  const stats = kit.corpusStats.map((s) => `  - ${s.value} — ${s.label}`).join("\n");
  return `You are a senior product designer + front-end engineer building a polished, BESPOKE AI-demo landing page for a specific medical clinic. It will be sent to a real prospect — make it look like a senior designer built it for THIS clinic, not a template.

═══ OUTPUT (non-negotiable) ═══
- Output ONLY raw HTML. NO markdown, NO \`\`\` fences, NO commentary. Start with <!DOCTYPE html>.
- ONE self-contained file. The ONLY external resources allowed: Tailwind via <script src="https://cdn.tailwindcss.com"></script>, the brand Google-Fonts <link>, and the single chat <iframe>. No other scripts, no placeholder/lorem text, no invented content.
- Fully responsive (mobile-first). Accessible: semantic landmarks, alt text on images, sufficient contrast.

═══ HARD RULES (these caused real bugs — do not break) ═══
1. The top header/nav bar MUST have a SOLID DEEP background using the primary color (literal \`background:${kit.palette.primary}\`). ALWAYS — never a light/white/cream header. The logo is light/white, so a light header makes it invisible. White nav text on the dark bar.
2. COLORS: use LITERAL hex values via inline \`style\` or arbitrary Tailwind (e.g. \`bg-[${kit.palette.primary}]\`, \`text-[${kit.palette.accent}]\`). Do NOT invent custom Tailwind color names like \`bg-cream\`/\`bg-primary\`/\`text-navy\` — they don't exist in the CDN build and silently render as nothing.
3. Use ONLY the facts below. Do NOT invent stats, awards, testimonials, years, phone numbers, addresses, or services. No claims beyond the value prop + stats given.
4. ${kit.hasLogin ? "The clinic has a patient login — you MAY add a single subtle \"Log in\" link in the header." : "The clinic has NO patient login — do NOT add any \"Log in\" / member / sign-in link anywhere."}
5. Education-only compliance: include one line stating the AI provides education only, never diagnoses, and points patients to a consultation.
6. Load the brand font and apply it everywhere. Use the brand palette consistently — primary (dark) for the header + headlines, accent for CTAs/links.
7. Every button/CTA (especially the header "Ask the AI") MUST be \`white-space:nowrap\` and \`flex-shrink:0\` so its label never wraps to two lines on narrow/mobile widths.
8. TEAM AVATAR PARITY: photo avatars and initials-fallback avatars MUST be the SAME diameter AND share the SAME ring. Give BOTH a \`border:3px solid <primary>\` ring. The initials fallback uses a LIGHT tinted fill (e.g. a very light neutral/blue-gray) with the initials in the PRIMARY (dark) color — NOT a heavy solid-dark disk, which reads visually larger/heavier than the photos beside it.

═══ BRAND KIT (use exactly) ═══
- Org: ${kit.org}    |  AI product name: ${kit.productName}
- Hero headline (tagline): "${kit.tagline}"   |  Subhead/value prop: ${kit.valueProp}
- Palette: primary ${kit.palette.primary}, accent ${kit.palette.accent}, mid ${kit.palette.mid}, cream ${kit.palette.cream}, soft ${kit.palette.soft}, text ${kit.palette.text}.
- Font: ${kit.fontFamily}${kit.fontLink ? ` — load: ${kit.fontLink}` : ""}
- Logo (img): ${kit.logoUrl}
- Corpus proof stats:\n${stats}
- Team:\n${team}
- Main site (footer link): ${kit.mainSite}

═══ THE CHAT (centerpiece) ═══
Embed the live chat as a prominent, well-framed iframe in the hero — a rounded "chat console" card with a subtle brand border + shadow. The card MUST have a small window-chrome header bar at the very top (inside the card, ABOVE the iframe): three traffic-light dots on the left (red \`#ff5f57\`, amber \`#febc2e\`, green \`#28c840\`, ~0.7rem circles) followed by the product name "${kit.productName}" in the primary color — like a little embed/browser window. Then the iframe BELOW that header:
<iframe src="${kit.embedUrl}" title="${kit.productName}" loading="eager" style="width:100%;height:560px;max-height:72vh;border:0;border-radius:1rem;" allow="clipboard-write"></iframe>
Do NOT add your own chat input — the iframe IS the chat. Frame it; put the headline + value prop above it.

═══ SECTIONS (exact order) ═══
1. Sticky header bar (primary color): logo img (sized generously — about \`h-11\`/44px, NOT a tiny \`h-8\`; a circular logo must stay legible) + "${kit.productName}" wordmark; nav anchors to #how / #team; an accent "Ask the AI" button linking to the hero chat.
2. Hero: ${kit.heroImageUrl ? `the hero \`<section>\` is \`position:relative; overflow:hidden\` with a RECOGNIZABLE faded illustration background: \`<img src="${kit.heroImageUrl}">\` absolutely positioned \`inset-0\`, \`object-cover\`, SOFTLY blurred a little (\`filter:blur(5px)\` — a gentle soft blur, NOT razor-sharp and NOT a heavy 40px smear), opacity ~0.5, \`pointer-events-none\`, BEHIND the content (z-index:0 / first child). The illustration stays recognizable and frames the open center. ALL hero content sits above it (\`position:relative; z-10\`). Do NOT add any background panel/card/box behind the text block. Instead make the TEXT ITSELF highlighted — a glassy translucent background that hugs each line of text like a highlighter marker: put the headline text in an inline \`<span>\` and the subhead text in an inline \`<span>\` with \`display:inline; box-decoration-break:clone; -webkit-box-decoration-break:clone; background:rgba(255,255,255,0.55); padding:0.08em 0.32em; border-radius:0.3em;\` and give the \`<h1>\`/subhead generous \`line-height\` (~1.4) so the per-line highlight bands don't collide. The highlight is a glassy semi-transparent version of the hero section's near-white background color. The \`<h1>\` and subhead stay block-level + centered (only the inner text span carries the highlight). The LIVE badge keeps its own pill background; the chat console is its own white card below. Then: ` : ""}a small "LIVE · trained only on ${kit.org} content" badge, the tagline "${kit.tagline}" as a large bold display headline${kit.heroImageUrl ? " — BALANCE it across two lines with a \`<br>\` so the FINAL sentence sits on its own line (e.g. first sentence(s) on line 1, the last sentence on line 2), and wrap EACH line's text in its OWN inline \`.hl\` highlight span (one span per line, NOT the whole headline in a single span)" : ""}, the value-prop subhead${kit.heroImageUrl ? " (subhead text in an inline highlighted span)" : ""}${kit.heroImageUrl ? "" : ", then the chat iframe console"}.
2b. Hero spacing: keep the hero's TOP padding very small (about \`pt-2\`/\`pt-3\`, never \`pt-12\`+) so the content sits HIGH right under the header and most of the chat console is visible on first load without scrolling.
3. #how "Built on ${kit.org}'s published content": ${kit.corpusVideo ? "a TWO-COLUMN row that stacks on mobile — LEFT column = the eyebrow + headline + description; RIGHT column (a bit UNDER half the width, e.g. 5 of 12 cols) = the EXACT literal line \`<!--CORPUS_VIDEO-->\` on its own line (a framed corpus video is spliced there — do NOT add your own video or placeholder). BELOW that row: " : "the intro/description, then "}the corpus stats as cards + the education-only compliance line. After the stats, add the EXACT literal line \`<!--LANGUAGE_PILLS-->\` on its own line — a supported-language display is spliced in there.
${kit.transcript ? `4. Example conversation: place the EXACT literal line \`<!--EXAMPLE_CHAT-->\` on its own line here (between #how and #team). A pre-rendered, grounded example-chat section is spliced in at this marker — do NOT write any conversation, transcript, questions, or answers yourself.

` : ""}5. #team ${kit.team.length === 1 ? `heading "Meet ${kit.team[0].name}" (NOT "Meet the team" — there is only one person)` : `"Meet the team"`}: ${kit.team.length === 1 ? "ONE large, prominent, CENTERED card (max-width ~28rem, mx-auto, generous padding; a LARGE headshot ~7rem and larger name/title) — do NOT make it a small left-aligned card" : kit.team.length === 2 ? "TWO large cards, centered side by side (each generously sized, ~50% width on desktop, stacking on mobile)" : "a responsive grid of member cards"} (each: photo if given, else the initials-fallback avatar from rule 8 — primary ring + light tinted fill + primary initials, NOT a solid dark disk; name + title).
${kit.featureVideos && (kit.featureVideos.mobileApp || kit.featureVideos.offline) ? `6. #coming "What's coming next": a two-up feature grid. Each card = a looping autoplay video (muted, loop, playsinline, preload="metadata", poster=the poster url, rounded, brand border, aspect-[16/10] object-cover) + a small badge row + a bold title + a short body. Use these EXACT videos:
${kit.featureVideos.mobileApp ? `   • Card A — badges "iPhone" + "Android"; title "Native mobile app with photo recognition"; body "Snap a photo of a report, scan, or handout and ${kit.productName} explains it in plain language — education only, and it points you to the right next step." video <video src="${kit.featureVideos.mobileApp.videoUrl}" poster="${kit.featureVideos.mobileApp.posterUrl}" autoplay muted loop playsinline preload="metadata">` : ""}
${kit.featureVideos.offline ? `   • Card B — badge "On-device"; title "${kit.productName}, running on your device"; body "A compressed on-device version that answers your questions with no connection required." video <video src="${kit.featureVideos.offline.videoUrl}" poster="${kit.featureVideos.offline.posterUrl}" autoplay muted loop playsinline preload="metadata">` : ""}
   (These are "coming soon" — frame them aspirationally, e.g. a "Coming soon" eyebrow.)
` : ""}6b. QA test results: place the EXACT literal line \`<!--QA_RESULTS-->\` on its own line here — a scored-QA-results display is spliced in at this marker. Do NOT add any QA display yourself.
7. CTA section (primary gradient): "Ready to ask ${kit.productName}?" + a button that scrolls to the hero chat${kit.hasLogin ? "" : " (no login link)"}.
8. Footer: © ${kit.org} + current year, "Powered by Divinci AI", and the main-site link.

Make it genuinely premium, calm, and trustworthy — a clinical brand.`;
}

/** Run claude -p with the prompt → validated raw HTML written to outPath. */
export function generateFoundation(kit: FoundationKit, outPath: string): string {
  const prompt = buildFoundationPrompt(kit);
  let html = runClaudeSync(prompt);
  // Strip any stray markdown fences the model may add despite instructions.
  html = html.trim().replace(/^```html\s*/i, "").replace(/^```\s*/, "").replace(/\s*```$/, "").trim();
  if (!/^<!doctype html>/i.test(html) || !/<\/html>\s*$/i.test(html)) {
    throw new Error(`generated foundation is not a complete HTML document (got ${html.slice(0, 60)}…)`);
  }
  if (!html.includes(kit.embedUrl)) throw new Error("generated foundation is missing the chat iframe");
  // Splice the example-chat (transcript showcase) in deterministically — never
  // generated by the LLM (citation markup is too easy to mangle).
  if (kit.transcript) {
    const section = renderExampleChat(kit.transcript, {
      productName: kit.productName,
      siteName: kit.org,
      palette: kit.palette,
      logoUrl: kit.logoUrl,
      logoIsLight: kit.logoIsLight,
      avatarImageUrl: kit.team.find((m) => m.image)?.image, // lead practitioner's face
      welcomeMessage: kit.welcomeMessage ?? `Hi! I'm the ${kit.productName}. Ask me anything.`,
      heroAnchor: "#top",
    });
    html = injectExampleChat(html, section);
    if (!html.includes('id="example"')) throw new Error("failed to inject example-chat section");
  }
  // Deterministic polish pass — bulletproof, independent of how the one-shot
  // generation rendered. Includes corpus video, header no-wrap, mobile nav,
  // hero animation, language switcher, example cards, language pills, QA results.
  html = polishFoundation(html, {
    palette: kit.palette,
    corpusVideo: kit.corpusVideo,
    team: { count: kit.team.length, leadName: kit.team[0]?.name },
    heroImageUrl: kit.heroImageUrl,
    logoIsLight: kit.logoIsLight,
    productName: kit.productName,
    embedUrl: kit.embedUrl,
    conversationStarters: kit.conversationStarters,
    qaScore: kit.qaScore,
    qaPassedCount: kit.qaPassedCount,
    qaTestCount: kit.qaTestCount,
    qaRunId: kit.qaRunId,
    qaSuiteId: kit.qaSuiteId,
    workspaceId: kit.workspaceId,
    // links omitted → injectFooterLegal uses Divinci's shared legal URLs
    // (same defaults as the template Footer.astro).
  });
  writeFileSync(outPath, html);
  return html;
}
